
select MLSTN_ID,MLSTN_NAME from ENGAGEMENT.EDB_MILESTONE where PROJ_ID=3


SELECT l.EMP_ID,e.EMP_ROLE,e.EMP_ENTERPRISE_ID 
from ENGAGEMENT.EDB_LOGIN l 
	join ENGAGEMENT.EDB_EMP_DTLS e on e.EMP_ID=l.EMP_ID 
where e.EMP_ID=10302547 and l.EMP_PASS='password'

insert into ENGAGEMENT.CLNT_ENGMNT (CLNT_ID, CLNT_NM, CLNT_TYP, CLNT_ST_DT)
VALUES (1, 'HCSC', 'HEALTH CARE', '2014-01-01');

select * from ENGAGEMENT.EDB_PROJECT;

select * from ENGAGEMENT.CLNT_ENGMNT;

select EMP_ENTERPRISE_ID from ENGAGEMENT.EDB_MSTR_EMP_DTLS where EMP_EMPLOYEE_ID='10302547'